channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - click=8.0.3
  - cycler=0.11.0
  - dash=1.19.0
  - dash-core-components=1.3.1
  - dash-html-components=1.0.1
  - dash-renderer=1.1.2
  - dash-table=4.4.1
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.1
  - flask=2.0.2
  - flask-compress=1.5.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.4
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - plotly=5.1.0
  - pycparser=2.21
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.36.0
  - tenacity=8.0.1
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2021e
  - werkzeug=2.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9