name: cluster_pval

channels:
  - defaults
  - conda-forge
  - bioconda
  
dependencies:
  - numpy=1.21.2
  - pandas=1.3.4
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - dash=1.19.0
  - dash-core-components=1.3.1
  - dash-table=4.4.1
  - dash-html-components=1.0.1
  - plotly=5.1.0