name: test-environment
channels:
  - defaults
  - conda-forge
  - bioconda
  
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - dash
  - dash-core-components
  - dash-table
  - dash-html-components
  - umap-learn
  - plotly